### ISSUE TITLE
it is recommended to add customization to the character upnp-org in helpers.ts.

### ISSUE THREAD

**Issue by colorhacker** [Mikescops/upnp-client-ts#5]
urn:upnp-org:serviceId: is the current default ,however, not all devices have this definition, because this definition can be modified by yourself.
ex：
urn:schemas-upnp-org:service:AVTransport:1

**Comment by Mikescops** [comment]
Good to know, thanks!
If you want to do a PR for it I'll take it, otherwise I'll do it a bit later, I have a few other work on plate right now.

**Comment by colorhacker** [comment]
i read the code carefully and found that no modification is needed, thank you!
i will continue to use this library later and submit a PR if there are fundamental problems. grateful.
